services:
  - type: web
    name: food-delivery-app  # Change this to your desired service name
    env: node
    buildCommand: npm run build
    startCommand: npm start
    routes:
      - src: /(.*)
        dest: /index.html  # Redirect all requests to index.html
